- name: Say Hello
  hosts: all
  tasks:
    - name: say hello
      ansible.builtin.debug:
        msg: Say hello to everyone

- name: Say Bye
  hosts: all
  tasks:
    - name: say bye
      ansible.builtin.debug:
        msg: Say bye to everyone
