#- name: filter demo
#  hosts: localhost
#  tasks:
#    - name: convert string to uppercase
#      ansible.builtin.debug:
#       msg: "{{ 'ansible' | upper }}"   # Output: ANSIBLE


- name: URL Parsing using Filters
  hosts: localhost
  vars:
    website_url: "https://example.com/data/files/archive.tar.gz"

  tasks:
    - name: Show original URL
      debug:
        msg: "Full URL: {{ website_url }}"

    - name: Extract protocol
      debug:
        msg: "Protocol: {{ website_url.split('://')[0] }}"

    - name: Extract domain
      debug:
        msg: "Domain: {{ website_url.split('://')[1].split('/')[0] }}"

    - name: Extract path
      debug:
        msg: "Path: /{{ website_url.split('://')[1].split('/', 1)[1] | regex_replace('/[^/]+$', '') }}"

    - name: Extract filename
      debug:
        msg: "Filename: {{ website_url | regex_search('[^/]+$') }}"

