- name:  Print the value from ssm
  hosts: localhost
  tasks:
    - name: Print value of test
      ansible.builtin.debug:
        msg: "{{ lookup('amazon.aws.aws_ssm', 'test', region='us-east-1' ) }}"