- name: handlers demo
  hosts: localhost
  tasks:
    - name: copy sample
      ansible.builtin.template:
        src: hello.txt
        dest: /tmp/hello.txt
        remote_src: yes
      notify: say hello again

    - name: say hello again
      ansible.builtin.debug:
        msg: hello {{ name }} again.





