- name: handlers demo
  hosts: localhost
  tasks:
    - name: copy sample
      ansible.builtin.template:
        src: teju.txt
        dest: /tmp/teju.txt
        remote_src: yes

    - name: say hello again
      ansible.builtin.debug:
        msg: hello {{ name }} again.




