- name: Demo of ignore
  hosts: localhost
  tasks:
    - name: Run the shell command
      ansible.builtin.shell: exit 1
      ignore_errors: true

    - name: Say Hi
      ansible.builtin.debug:
        msg: hai