- name: Demo on Vars
  hosts: localhost
  #if we declare variable here(play book) then all the tasks can access this variable
  vars:
    URL: play.google.com
  tasks:
    - name: Print play level variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Print variable declared in task
      vars:
        URL: task.google.com
        ansible.builtin.debug:
          msg: URL = {{ URL }}

  roles:
    - demo
